# Dockerfile.llm
FROM python:3.10-slim

RUN apt-get update && apt-get install -y git curl && rm -rf /var/lib/apt/lists/*

WORKDIR /app
# Ajouter /app au PYTHONPATH
ENV PYTHONPATH=/app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copier TOUT le dossier `src` et son contenu dans /app/src sauf api.py
COPY src/__init__.py src/get_embedding.py src/populate_database.py src/query_data.py src/rag_llm_services.py /app/src/

EXPOSE 5001

# Lancer le service LLM
CMD ["python", "src/rag_llm_services.py"]