# Dockerfile.api
FROM python:3.10-slim

RUN apt-get update && apt-get install -y git curl && rm -rf /var/lib/apt/lists/*

WORKDIR /app
# Ajouter /app au PYTHONPATH
ENV PYTHONPATH=/app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copier api.py dans le dossier `src` et son contenu dans /app/src
COPY src/api.py /app/src/

EXPOSE 5002

# Lancer l'API
CMD ["python", "src/api.py"]