# Dockerfile.frontend
FROM python:3.10-slim

# Set the working directory to /app
WORKDIR /app

# Copy the requirements file into the working directory
COPY requirements.txt .
# Install the Python dependencies specified in requirements.txt without caching to reduce image size
RUN pip install --no-cache-dir -r requirements.txt

# Copy the Python script "frontend.py" from the "src" directory into /app
COPY src/frontend.py /app/

# Copy the entire "frontend" directory into /app/frontend
COPY frontend /app/frontend

# Expose port 5003 so that the frontend service can be accessed
EXPOSE 5003

# Set the default command to run the frontend Python script when the container starts
CMD ["python", "frontend.py"]
