# Kubernetes Service manifest for the API
apiVersion: v1                   # API version used for the Service resource
kind: Service                  # Specifies that this resource is a Service
metadata:
  name: api                    # Name of the service
spec:
  selector:
    app: api                   # Selects pods with the label "app: api" to route traffic to
  ports:
    - protocol: TCP            # Network protocol used for the port (TCP)
      port: 5002               # Port on which the service is exposed within the cluster
      targetPort: 5002         # Port on the pods to which the traffic will be forwarded
  type: ClusterIP              # Service type; ClusterIP exposes the service on an internal cluster IP
