# Kubernetes Service manifest for the Frontend service
apiVersion: v1               # API version for the Service resource
kind: Service              # Specifies that this resource is a Service
metadata:
  name: frontend           # Name of the service (used for DNS resolution within the cluster)
spec:
  selector:
    app: frontend          # Routes traffic to pods with the label "app: frontend"
  ports:
    - protocol: TCP        # Specifies that the service uses the TCP protocol
      port: 5003           # Port on which the service is exposed externally or within the cluster
      targetPort: 5003     # Port on the pod that the service forwards traffic to (must match the container port)
  type: LoadBalancer       # Service type that exposes the service externally using a cloud provider's load balancer
