apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: mgn94/infrastructure-rag-llm:frontend-service-latest
          ports:
            - containerPort: 5003
          livenessProbe:
            httpGet:
              path: /
              port: 5003
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 5003
            initialDelaySeconds: 5
            periodSeconds: 10
      imagePullSecrets:
        - name: my-registry-secret
