# Kubernetes Service manifest for the LLM service
apiVersion: v1                # API version for the Service resource
kind: Service               # Specifies that this resource is a Service
metadata:
  name: llm                 # Name of the service (used for internal DNS resolution within the cluster)
spec:
  selector:
    app: llm                # Selects pods with the label "app: llm" to route traffic to
  ports:
    - protocol: TCP         # Specifies that the service uses the TCP protocol
      port: 5001            # Port on which the service is exposed within the cluster
      targetPort: 5001      # Port on the pod to which traffic will be forwarded (must match the container's exposed port)
  type: ClusterIP           # Service type that exposes the service on an internal cluster IP
