# Helm Chart definition for deploying a RAG LLM, its microservices, and the monitoring stack
apiVersion: v2
name: rag-llm
description: Helm chart to deploy a RAG LLM, its microservices, and the monitoring stack
version: 0.1.0

# Dependencies for Prometheus and Grafana
dependencies:
  - name: prometheus
    version: "~15.0.0" # Use this version or a newer one if required
    repository: "https://prometheus-community.github.io/helm-charts"

  - name: grafana
    version: "~7.0.0" # Use a version >= 7.0.0 to avoid issues with Pod Security Policies (PSP)
    repository: "https://grafana.github.io/helm-charts"
