apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
      annotations:
{{- if .Values.prometheusScrape.enabled }}
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.api.port }}"
        prometheus.io/path: "{{ .Values.api.metricsPath }}"
        prometheus.io/scheme: "{{ .Values.prometheusScrape.scheme }}"
{{- end }}
    spec:
      containers:
        - name: api
          image: "{{ .Values.api.image }}"
          ports:
            - containerPort: {{ .Values.api.port }}
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: {{ .Values.api.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: {{ .Values.api.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
      imagePullSecrets:
{{- range .Values.imagePullSecrets }}
      - name: {{ . }}
{{- end }}
