# Kubernetes Service manifest for the Chroma application
apiVersion: v1
kind: Service
metadata:
  name: chroma                # Name of the service
  labels:
    app: chroma               # Label to identify the Chroma application
spec:
  selector:
    app: chroma               # Selects pods with the label "app: chroma" to be part of this service
  ports:
    - protocol: TCP           # Specifies that the service uses TCP protocol
      port: {{ .Values.chroma.port }}       # Port on which the service is exposed (from Helm values)
      targetPort: {{ .Values.chroma.port }} # Port on the pod that the service will forward traffic to (must match the container port)
  type: ClusterIP             # Service type that exposes the service on an internal IP within the cluster
