apiVersion: v1
kind: Service
metadata:
  name: chroma
  labels:
    app: chroma
spec:
  selector:
    app: chroma
  ports:
    - protocol: TCP
      port: {{ .Values.chroma.port }}
      targetPort: {{ .Values.chroma.port }}
  type: ClusterIP
