apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-deployment
  labels:
    app: llm
spec:
  replicas: {{ .Values.llm.replicas }}
  selector:
    matchLabels:
      app: llm
  template:
    metadata:
      labels:
        app: llm
      annotations:
{{- if .Values.prometheusScrape.enabled }}
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.llm.port }}"
        prometheus.io/path: "{{ .Values.llm.metricsPath }}"
        prometheus.io/scheme: "{{ .Values.prometheusScrape.scheme }}"
{{- end }}
    spec:
      containers:
        - name: llm
          image: "{{ .Values.llm.image }}"
          ports:
            - containerPort: {{ .Values.llm.port }}
          env:
            - name: PYTHONPATH
              value: /app
      imagePullSecrets:
{{- range .Values.imagePullSecrets }}
      - name: {{ . }}
{{- end }}
