apiVersion: v1
kind: Service
metadata:
  name: llm
  labels:
    app: llm
spec:
  selector:
    app: llm
  ports:
    - protocol: TCP
      port: {{ .Values.llm.port }}
      targetPort: {{ .Values.llm.port }}
  type: ClusterIP
