name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Configure Docker Hub credentials
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build and push the LLM Service Docker image
      - name: Build and Push LLM Service Image
        run: |
          docker build -t mgn94/infrastructure-rag-llm:llm-service-latest -f dockerfile.rag_llm .
          docker push mgn94/infrastructure-rag-llm:llm-service-latest

      # Build and push the API Service Docker image
      - name: Build and Push API Service Image
        run: |
          docker build -t mgn94/infrastructure-rag-llm:api-service-latest -f dockerfile.api .
          docker push mgn94/infrastructure-rag-llm:api-service-latest

      # Build and push the Frontend Service Docker image
      - name: Build and Push Frontend Service Image
        run: |
          docker build -t mgn94/infrastructure-rag-llm:frontend-service-latest -f dockerfile.frontend .
          docker push mgn94/infrastructure-rag-llm:frontend-service-latest

      # Build and push the Chroma Service Docker image
      - name: Build and Push Chroma Service Image
        run: |
          docker build -t mgn94/infrastructure-rag-llm:chroma-service-latest -f dockerfile.chroma .
          docker push mgn94/infrastructure-rag-llm:chroma-service-latest

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      # Check out the repository code (required for deployment)
      - name: Checkout Code
        uses: actions/checkout@v3

      # Deployment step (adapt this command to your deployment method, e.g., Docker Compose, SSH, etc.)
      - name: Deploy to Production
        run: |
          echo "Run deployment commands here, for example using Docker Compose or SSH."
